Add Phala Network crowdloan info
itering/parachain-projects-info pull request #28
Opened 2021-12-27 18:12 UTC by h4x3rotab

2021-12-28 01:44 UTC, carlhong requested changes
Please add a description for your pr, the description includes the original data of the signature, signature account, and signature.

2021-12-28 12:40 UTC, jasl commented
@carlhong Hi we just updated the description, please review again, thanks

2021-12-29 01:51 UTC, carlhong commented
![image](https://user-images.githubusercontent.com/11582958/147619899-757a9009-7c57-4da9-83e0-ba63071132a1.png)
Verified!

2021-12-29 01:51 UTC, carlhong approved these changes

2021-12-29 01:51 UTC, merged